export const NEW_MESSAGE_REQUEST = "NEW_MESSAGE_REQUEST";
export const NEW_MESSAGE_SUCCESS = "NEW_MESSAGE_SUCCESS";
export const NEW_MESSAGE_FAIL = "NEW_MESSAGE_FAIL";

export const ALL_MESSAGES_REQUEST = "ALL_MESSAGES_REQUEST";
export const ALL_MESSAGES_SUCCESS = "ALL_MESSAGES_SUCCESS";
export const ALL_MESSAGES_FAIL = "ALL_MESSAGES_FAIL";

export const SINGLE_MESSAGE_REQUEST = "SINGLE_MESSAGE_REQUEST";
export const SINGLE_MESSAGE_SUCCESS = "SINGLE_MESSAGE_SUCCESS";
export const SINGLE_MESSAGE_FAIL = "SINGLE_MESSAGE_FAIL";

export const CONFIRM_MESSAGE_REQUEST = "CONFIRM_MESSAGE_REQUEST";
export const CONFIRM_MESSAGE_SUCCESS = "CONFIRM_MESSAGE_SUCCESS";
export const CONFIRM_MESSAGE_FAIL = "CONFIRM_MESSAGE_FAIL";

export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL";
